### ISSUE TITLE
New Api to check if the transaction is on the blockchain.

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [elastos/Elastos.ORG.ElaPay#3]
### API: /api/gettxdetailsforcallback
- Method: Get
- Request params:
```javascript
txhash,
orderId
```
- [tips] using orderId to get callbackurl from collection orders
- [tips] check if  the tx is in the blockchain
- [tips] check tx.output[0].Value is the same as order.elaAmount 
- [tips] check the Buffer.from(transaction.Result.Attributes.Data,'hex').toString('utf8') equals to orderId .
- [tips] if all true then the tx is on the blockchain else it is not on the blockchain.

- Response: code: 200,status,details .

**Comment by SharedMocha** [comment]
Fix : Modify fetchblock.js to save atrribute.date(orderid) and then modify the api to accept txhash,orderid to check against the data stored

**Comment by SharedMocha** [comment]
This issue is now fixed-
We are only comparing txhash and orderid. Amount is not needed because txhash and orderid when present on blockchain gives the output that tx is present.
FilemModified:-fetchblocks.js
NewFileAdded:-checktx.js

Example - http://localhost:3002/api/checktx/?txhash=9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f&orderid=ELA
Output -
{
"status": "Not Success",
"action": "CheckIfTransactionPresent",
"details": "TX hash is in-valid or not presnt in blockkhain yet"
}

Example - http://localhost:3002/api/checktx/?txhash=9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f&orderid=ELA
Output-
{"status":"Success","action":"CheckIfTransactionPresent","txHash":"9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f","trackingURL":"http://blockchain-test-05.eadd.co/tx/9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f"}

**Comment by xiaomingfuckeasylife** [comment]
the thing is that when people can know the orderId . then people can forgy the transaction .sending less ela to the receiver address with the same orderId memo. then if you only check the txId and orderId . they found both right , if you consider the transaction is onchain .then people successfully make a forgery.

**Comment by SharedMocha** [comment]
Amount is now added to the criteria-
Input-
http://localhost:3002/api/checktx/?txhash=9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f&orderid=ELA

Output-
{"status":"Success","action":"CheckIfTransactionPresent","txHash":"9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f","trackingURL":"http://blockchain-test-05.eadd.co/tx/9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f"}

**Comment by xiaomingfuckeasylife** [comment]
```js
subQuery["orderName"] = orderid;
```
- should using `subQuery["_id"]` to match orderId 

- the ela-wallet will only call you once . so this is also subscribe api . the callback url can be fetched from orders collection too.

**Comment by xiaomingfuckeasylife** [comment]
No , you don't need to return the callback url , you need to return all this 
```json
{"status":"Success","action":"CheckIfTransactionPresent","txHash":"9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f","trackingURL":"http://blockchain-test-05.eadd.co/tx/9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f"}
```
to the callback url . 

just like the api ‘posttxdetailsforcallback’

**Comment by SharedMocha** [comment]
This issue is fixed-
Step1:- Make a GET call by passing txid and orderid
http://localhost:3002/api/checktx/?txhash=9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531f&orderid=5b043b85aae71730b00F4e29
Output-
{"status":"Success","action":"CheckIfTransactionPresent","details":"A callback request will be sent when transaction is avilable on blockchain."}

Step2:-You will receive a POST call when tx is present on blockchain to your callback url
Output-
{"transactionHash":"9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531g","trackingURL":"http://blockchain-test-05.eadd.co/tx/9acb57f462ac2c6132e67eec044f7dcbde93287b4a65f43b9a7a21dafa64531g","details":"Transaction is now present on blockchain","status":" Success","action":"GetTransactionsDetailsByHashToCallbackURL"}

**Comment by xiaomingfuckeasylife** [comment]
thanks .
